### ISSUE TITLE
Valor de catálogo

### ISSUE THREAD

**Issue by pcortesp** [PDNMX/catalogos#10]
En "tipo de fideicomiso", el validador indica que el valor "PÚBLICO" es incorrecto.
En "documento obtenido" el validador indica que el valor "TÍTULO" es incorrecto.
En "escolaridad nivel" el validador indica que la descripción "MAESTRÍA" es incorrecta.
¿Cuáles son los valores que se deben utilizar para cada caso?

**Comment by RazielSystems** [comment]
se realizaron los ajustes a los catálogos y se limpio en el estándar los datos que contenían información en otra codificación.

agradecemos tu cooperación para tener catálogos mas limpios y congruentes al estándar.

saludos!!!
