### ISSUE TITLE
Catálogo S3 Tipo sanción

### ISSUE THREAD

**Issue by w3ro** [PDNMX/catalogos#9]
Errores tipográficos en los siguientes atributos:
{ "clave": "S", "valor": "SUSPENSIÓN DEL EMPLEO, CARGO O COMISIÓ**N**" }
{ "clave": "D", "valor": "DESTITUCIÓN DEL EMPL**E**O, CARGO O COMISIÓN" }

**Comment by RazielSystems** [comment]
@w3ro Muchas gracias por tus observaciones, los cambios ya fueron realizados.

Saludos!!!!
